---
version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 8
  method-complexity:
    enabled: true
    config:
      threshold: 10
  file-lines:
    enabled: true
    config:
      threshold: 600
  method-lines:
    enabled: false
  method-count:
    enabled: false
  similar-code:
    enabled: true
  identical-code:
    enabled: true
  nested-control-flow:
    enabled: true
    config:
      threshold: 3
plugins:
  nodesecurity:
    enabled: true
exclude_patterns:
  - ".github"
  - "**/node_modules"
  - "**/*.test.js"
  - "plugins/conway"
  - ".browserslistrc"
  - ".codeclimate.yml"
  - ".gitignore"
  - ".prettierrc"
  - "eslint.config.js"
  - "jest.config.js"
  - "nuxt.config.js"
  - "package.json"
  - "README.md"
  - "yarn.lock"
