[package]
name = "@only-web/conway"
version = "0.2.0"
edition = "2022"

[lib]
crate-type = ["cdylib", "rlib"]
name = "conway"
path = "conway.rs"

# TODO: update rust version and dependencies
[dependencies]
fixedbitset = "0.2"
js-sys = "0.3"
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.2"

[profile.release]
lto = true
opt-level = "z"
