name: "Development Checks"

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checks:
    name: Development Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          cache: yarn

      - name: Run Checks
        run: yarn checks
  pull-request-size-label:
    name: Size Label
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/size-label-action@v0.4.3"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORED: |
            **/*.test.js
            plugins/conway
            .github
            .browserslistrc
            .codeclimate.yml
            .gitignore
            .prettierrc
            eslint.config.js
            jest.config.js
            nuxt.config.js
            package.json
            README.md
            yarn.lock
