---
jobs:
  size_label:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Change Size Label
    runs-on: ubuntu-latest
    steps:
      - name: Apply Size Label
        uses: pascalgn/size-label-action@a4655c448bb838e8d73b81e97fd0831bb4cbda1e
        with:
          sizes: >
            {
              "0": "XS",
              "64": "S",
              "128": "M",
              "256": "L",
              "512": "XL",
              "1024": "XXL"
            }

name: PR Checks
"on":
  pull_request:
    types:
      - opened
      - edited
      - synchronize
